name: Azure DevOps Login
description: Uses the az tool to login provide Azure DevOps authentication in GitHub Actions
author: EchelonFour

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: log-in
  color: blue

# Define your inputs here.
inputs:
  npmrc:
    description: comma separated list of npmrc files to read for logging in
    required: true
    default: '.npmrc'
  nuget:
    description: comma separated list of nuget sources to read for logging in
    required: true
    default: 'nuget.config'
  login-urls:
    description: comma separated list of Azure DevOps organization URLs to login to. Setting this overrides reading from npmrc and nuget files.
    required: false
    default: ''
  install-provider:
    description: Whether to install the Azure Artifacts Credential Provider
    required: false
    default: true

runs:
  using: node24
  main: dist/index.js
