name: Azure DevOps Login
description: Uses the az tool to login provide Azure DevOps authentication in GitHub Actions
author: EchelonFour

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: log-in
  color: blue

# Define your inputs here.
inputs:
  npmrc:
    description: comma separated list of npmrc files to read for logging in
    required: true
    default: '.npmrc'
  nuget:
    description: comma separated list of nuget sources to read for logging in
    required: true
    default: 'nuget.config'
  login-urls:
    description: |
      comma separated list of Azure DevOps organization URLs to login to.
      Setting this overrides reading from npmrc and nuget files and will only output the VSS_NUGET_EXTERNAL_FEED_ENDPOINTS.
    required: false
    default: ''
  install-provider:
    description: Whether to force install the Azure Artifacts Credential Provider
    required: false
    default: false
  build-npmrc-credentials-file:
    description: Whether to build an .npmrc file with the credentials for use in later steps
    required: false
    default: true
  build-nuget-credentials-file:
    description: Whether to build a nuget.config file with the credentials for use in later steps
    required: false
    default: true
  client-id:
    description: 'ClientId of the Azure Service principal created to act as. If not set, will use the az cli logged in user'
    required: false
  tenant-id:
    description: 'TenantId of the Azure Service principal created to act as. If not set, will use the az cli logged in user'
    required: false
  audience:
    description: 'Provide audience field for access-token. Default value is api://AzureADTokenExchange'
    required: false
    default: 'api://AzureADTokenExchange'
outputs:
  token:
    description: The Azure DevOps access token retrieved
runs:
  using: node24
  main: dist/index.js
